// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autoagric/control/gain_scheduler_conf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto;
namespace autoagric {
namespace control {
class GainScheduler;
struct GainSchedulerDefaultTypeInternal;
extern GainSchedulerDefaultTypeInternal _GainScheduler_default_instance_;
class GainSchedulerInfo;
struct GainSchedulerInfoDefaultTypeInternal;
extern GainSchedulerInfoDefaultTypeInternal _GainSchedulerInfo_default_instance_;
}  // namespace control
}  // namespace autoagric
PROTOBUF_NAMESPACE_OPEN
template<> ::autoagric::control::GainScheduler* Arena::CreateMaybeMessage<::autoagric::control::GainScheduler>(Arena*);
template<> ::autoagric::control::GainSchedulerInfo* Arena::CreateMaybeMessage<::autoagric::control::GainSchedulerInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace autoagric {
namespace control {

// ===================================================================

class GainScheduler final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:autoagric.control.GainScheduler) */ {
 public:
  inline GainScheduler() : GainScheduler(nullptr) {}
  ~GainScheduler() override;
  explicit constexpr GainScheduler(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GainScheduler(const GainScheduler& from);
  GainScheduler(GainScheduler&& from) noexcept
    : GainScheduler() {
    *this = ::std::move(from);
  }

  inline GainScheduler& operator=(const GainScheduler& from) {
    CopyFrom(from);
    return *this;
  }
  inline GainScheduler& operator=(GainScheduler&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GainScheduler& default_instance() {
    return *internal_default_instance();
  }
  static inline const GainScheduler* internal_default_instance() {
    return reinterpret_cast<const GainScheduler*>(
               &_GainScheduler_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GainScheduler& a, GainScheduler& b) {
    a.Swap(&b);
  }
  inline void Swap(GainScheduler* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GainScheduler* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GainScheduler* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GainScheduler>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GainScheduler& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GainScheduler& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GainScheduler* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "autoagric.control.GainScheduler";
  }
  protected:
  explicit GainScheduler(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSchedulerFieldNumber = 1,
  };
  // repeated .autoagric.control.GainSchedulerInfo scheduler = 1;
  int scheduler_size() const;
  private:
  int _internal_scheduler_size() const;
  public:
  void clear_scheduler();
  ::autoagric::control::GainSchedulerInfo* mutable_scheduler(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::autoagric::control::GainSchedulerInfo >*
      mutable_scheduler();
  private:
  const ::autoagric::control::GainSchedulerInfo& _internal_scheduler(int index) const;
  ::autoagric::control::GainSchedulerInfo* _internal_add_scheduler();
  public:
  const ::autoagric::control::GainSchedulerInfo& scheduler(int index) const;
  ::autoagric::control::GainSchedulerInfo* add_scheduler();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::autoagric::control::GainSchedulerInfo >&
      scheduler() const;

  // @@protoc_insertion_point(class_scope:autoagric.control.GainScheduler)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::autoagric::control::GainSchedulerInfo > scheduler_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto;
};
// -------------------------------------------------------------------

class GainSchedulerInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:autoagric.control.GainSchedulerInfo) */ {
 public:
  inline GainSchedulerInfo() : GainSchedulerInfo(nullptr) {}
  ~GainSchedulerInfo() override;
  explicit constexpr GainSchedulerInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GainSchedulerInfo(const GainSchedulerInfo& from);
  GainSchedulerInfo(GainSchedulerInfo&& from) noexcept
    : GainSchedulerInfo() {
    *this = ::std::move(from);
  }

  inline GainSchedulerInfo& operator=(const GainSchedulerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline GainSchedulerInfo& operator=(GainSchedulerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GainSchedulerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const GainSchedulerInfo* internal_default_instance() {
    return reinterpret_cast<const GainSchedulerInfo*>(
               &_GainSchedulerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GainSchedulerInfo& a, GainSchedulerInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(GainSchedulerInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GainSchedulerInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GainSchedulerInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GainSchedulerInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GainSchedulerInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GainSchedulerInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GainSchedulerInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "autoagric.control.GainSchedulerInfo";
  }
  protected:
  explicit GainSchedulerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kRatioFieldNumber = 2,
  };
  // double speed = 1;
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // double ratio = 2;
  void clear_ratio();
  double ratio() const;
  void set_ratio(double value);
  private:
  double _internal_ratio() const;
  void _internal_set_ratio(double value);
  public:

  // @@protoc_insertion_point(class_scope:autoagric.control.GainSchedulerInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double speed_;
  double ratio_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GainScheduler

// repeated .autoagric.control.GainSchedulerInfo scheduler = 1;
inline int GainScheduler::_internal_scheduler_size() const {
  return scheduler_.size();
}
inline int GainScheduler::scheduler_size() const {
  return _internal_scheduler_size();
}
inline void GainScheduler::clear_scheduler() {
  scheduler_.Clear();
}
inline ::autoagric::control::GainSchedulerInfo* GainScheduler::mutable_scheduler(int index) {
  // @@protoc_insertion_point(field_mutable:autoagric.control.GainScheduler.scheduler)
  return scheduler_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::autoagric::control::GainSchedulerInfo >*
GainScheduler::mutable_scheduler() {
  // @@protoc_insertion_point(field_mutable_list:autoagric.control.GainScheduler.scheduler)
  return &scheduler_;
}
inline const ::autoagric::control::GainSchedulerInfo& GainScheduler::_internal_scheduler(int index) const {
  return scheduler_.Get(index);
}
inline const ::autoagric::control::GainSchedulerInfo& GainScheduler::scheduler(int index) const {
  // @@protoc_insertion_point(field_get:autoagric.control.GainScheduler.scheduler)
  return _internal_scheduler(index);
}
inline ::autoagric::control::GainSchedulerInfo* GainScheduler::_internal_add_scheduler() {
  return scheduler_.Add();
}
inline ::autoagric::control::GainSchedulerInfo* GainScheduler::add_scheduler() {
  ::autoagric::control::GainSchedulerInfo* _add = _internal_add_scheduler();
  // @@protoc_insertion_point(field_add:autoagric.control.GainScheduler.scheduler)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::autoagric::control::GainSchedulerInfo >&
GainScheduler::scheduler() const {
  // @@protoc_insertion_point(field_list:autoagric.control.GainScheduler.scheduler)
  return scheduler_;
}

// -------------------------------------------------------------------

// GainSchedulerInfo

// double speed = 1;
inline void GainSchedulerInfo::clear_speed() {
  speed_ = 0;
}
inline double GainSchedulerInfo::_internal_speed() const {
  return speed_;
}
inline double GainSchedulerInfo::speed() const {
  // @@protoc_insertion_point(field_get:autoagric.control.GainSchedulerInfo.speed)
  return _internal_speed();
}
inline void GainSchedulerInfo::_internal_set_speed(double value) {
  
  speed_ = value;
}
inline void GainSchedulerInfo::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:autoagric.control.GainSchedulerInfo.speed)
}

// double ratio = 2;
inline void GainSchedulerInfo::clear_ratio() {
  ratio_ = 0;
}
inline double GainSchedulerInfo::_internal_ratio() const {
  return ratio_;
}
inline double GainSchedulerInfo::ratio() const {
  // @@protoc_insertion_point(field_get:autoagric.control.GainSchedulerInfo.ratio)
  return _internal_ratio();
}
inline void GainSchedulerInfo::_internal_set_ratio(double value) {
  
  ratio_ = value;
}
inline void GainSchedulerInfo::set_ratio(double value) {
  _internal_set_ratio(value);
  // @@protoc_insertion_point(field_set:autoagric.control.GainSchedulerInfo.ratio)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace control
}  // namespace autoagric

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_autoagric_2fcontrol_2fgain_5fscheduler_5fconf_2eproto
